// Labels are supplied by the workspace locale and contain no terminal content.
#[derive(Clone, Debug)]
pub struct TerminalReadingLabels {
    pub no_commands: String,
    pub no_results: String,

    pub exit_code: String,
    pub outline: String,
    pub search: String,
    pub all: String,
    pub failed: String,
    pub running: String,
    pub unknown: String,
    pub unavailable: String,
    pub truncated: String,
    pub preview: String,
    pub copy_command: String,
    pub copy_output: String,
    pub close: String,
    pub paste_edit: String,
    pub edit: String,
    pub paste: String,
    pub send_to_sender: String,
    pub cancel: String,
    pub undo: String,
    pub redo: String,
    pub remove_numbers: String,
    pub remove_prefix: String,
    pub prefix: String,
    pub tabs_to_spaces: String,
    pub spaces_to_tabs: String,
    pub lf: String,
    pub crlf: String,
    pub invalid_transform: String,
    pub tools: String,
    pub timestamp: String,
    pub utc: String,
    pub local: String,
    pub decimal: String,
    pub binary: String,
    pub copy: String,
    pub archive: String,
    pub path: String,
    pub shell: String,
    pub choose_shell: String,
    pub generate: String,
    pub markers: String,
    pub clear_markers: String,
    pub remove: String,
    pub save_rule: String,
    pub mark_selection: String,
    pub yellow: String,
    pub blue: String,
    pub green: String,
    pub pink: String,
    pub select_rule_set: String,
}

impl Default for TerminalReadingLabels {
    fn default() -> Self {
        Self {
            no_commands: "No command records yet".into(),
            no_results: "No matching commands".into(),

            exit_code: "Exit code".into(),
            outline: "Command outline".into(),
            search: "Search commands".into(),
            all: "All".into(),
            failed: "Failed".into(),
            running: "Running".into(),
            unknown: "Unknown status".into(),
            unavailable: "Output is no longer available".into(),
            truncated: "Preview truncated".into(),
            preview: "Output preview".into(),
            copy_command: "Copy command".into(),
            copy_output: "Copy output".into(),
            close: "Close".into(),
            paste_edit: "Paste and edit".into(),
            edit: "Edit".into(),
            paste: "Paste".into(),
            send_to_sender: "Open in advanced sender".into(),
            cancel: "Cancel".into(),
            undo: "Undo".into(),
            redo: "Redo".into(),
            remove_numbers: "Remove line numbers".into(),
            remove_prefix: "Remove prefix".into(),
            prefix: "Line prefix".into(),
            tabs_to_spaces: "Tabs to spaces".into(),
            spaces_to_tabs: "Spaces to tabs".into(),
            lf: "LF".into(),
            crlf: "CRLF".into(),
            invalid_transform: "Text does not match the selected conversion".into(),
            tools: "Text tools".into(),
            timestamp: "Timestamp".into(),
            utc: "UTC".into(),
            local: "Local time".into(),
            decimal: "Decimal".into(),
            binary: "Binary".into(),
            copy: "Copy".into(),
            archive: "Generate extraction command".into(),
            path: "Archive path".into(),
            shell: "Shell".into(),
            choose_shell: "Choose the target shell".into(),
            generate: "Generate".into(),
            markers: "Temporary markers".into(),
            clear_markers: "Clear all markers".into(),
            remove: "Remove".into(),
            save_rule: "Save as highlight rule".into(),
            mark_selection: "Mark selected text".into(),
            yellow: "Yellow".into(),
            blue: "Blue".into(),
            green: "Green".into(),
            pink: "Pink".into(),
            select_rule_set: "Select a highlight rule set".into(),
        }
    }
}
