[package]
name = "oxideterm-rdp-helper"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []

[dependencies]
ironrdp = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b", features = ["cliprdr", "connector", "displaycontrol", "dvc", "graphics", "input", "pdu", "session", "svc"] }
ironrdp-cliprdr-format = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b" }
ironrdp-core = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b" }
ironrdp-displaycontrol = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b" }
ironrdp-egfx = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b" }
ironrdp-graphics = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b" }
ironrdp-tls = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b", default-features = false, features = ["native-tls"] }
ironrdp-tokio = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "82c4acf89a173d38442f859e18963c39350ee74b", features = ["reqwest"] }
native-tls = { version = "0.2", features = ["vendored"] }
oxideterm-remote-desktop = { path = "../oxideterm-remote-desktop" }
semver = "1"
smallvec = "1"
tokio.workspace = true
zeroize.workspace = true
